services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita conflito com node_modules local
    networks:
      rede_interna:
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessário em ambientes como Windows/WSL2

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      rede_interna:
    depends_on:
      - database

  database:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    ports:
      - "3307:3306"
    networks:
      rede_interna:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  rede_interna:
